version: '2'
services:
   db:
     image: postgres
     container_name: db
     volumes:
       - "db-data:/var/lib/postgresql/data"
   web:
     build:
       context: ./web
       args:
         env: dev
     command: python manage.py runserver 0.0.0.0:8000
     environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
     volumes:
       - ./web:/app
     ports:
       - "8000:8000"
     depends_on:
       - db
   frontend:
     build:
       context: .
       dockerfile: ./frontend/Dockerfile
       args:
         env: dev
     command: sh -c "npm -q install && gulp watch"
     volumes:
       - ./web/ksupcapp/static:/static
       - ./frontend:/src
       - node-modules:/src/node_modules
       - bower-components:/src/bower_components


volumes:
  db-data:
  node-modules:
  bower-components: