version: '2'
services:
   db:
     image: postgres
     container_name: db
     volumes:
       - "db-data:/var/lib/postgresql/data"
   web:
     build: ./web
     volumes:
       - ./web:/app
     ports:
       - "8000:8000"
     depends_on:
       - db

volumes:
  db-data:
