# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20161121_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
