# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_remove_profile_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='profile',
            new_name='person',
        ),
    ]
