# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 19:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20161121_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumperProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uspa_number', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(1000000, message="I don't believe USPA numbers exist that are that high.")])),
                ('uspa_expiration_date', models.DateField()),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50, message="I'm calling bullshit.  You weigh more than that."), django.core.validators.MaxValueValidator(400, message="Let's talk about bowling.")])),
                ('number_of_skydives', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(help_text='The format <em>xxx-xxx-xxxx</em> is preferred.', max_length=12),
        ),
    ]
