# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20161121_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumperprofile',
            name='last_jump_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jumperprofile',
            name='number_of_skydives_here',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jumperprofile',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profile.Person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jumperprofile',
            name='uspa_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
