# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20161121_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Coach', (('C', 'Coach'),)), ('Instructor', (('SLI', 'Static Line Instructor'), ('IADI', 'Instructor Assisted Deployment Instructor'), ('AFFI', 'Accelerated Free Fall Instructor'), ('TI', 'Tandem Instructor'))), ('Instructor Examiner', (('CIE', 'Coach Examiner'), ('SLIE', 'Static Line Instructor Examiner'), ('IADIE', 'Instructor Assisted Deployment Instructor'), ('AFFI', 'Accelerated Free Fall Instructor'), ('TIE', 'Tandem Instructor Examiner'))), ('Safety and Training Advisor', (('STA', 'Safety and Training Advisor'),)), ('Pro', ('PRO', 'Pro'))], max_length=5)),
                ('expiration_date', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('jumper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.JumperProfile')),
            ],
        ),
    ]
