# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('number', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('jumper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.JumperProfile')),
            ],
        ),
    ]
